version: 2.1

jobs:
  build:
    filters:
      tags:
        only: /.*/
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build and Push Images
          command: |
            export REGISTRY=myagmarsurensedjav/laravel-docker
            export IMAGE_TAG=${CIRCLE_TAG}
            make build
            make push
