version: 2.1

jobs:
  publish-docker:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Docker Login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Docker Build
          command: |
            IMAGE_TAG=$CIRCLE_TAG make build
      - run:
          name: Docker Push
          command: |
            IMAGE_TAG=$CIRCLE_TAG make push

workflows:
  publish:
    jobs:
      - publish-docker:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
